name: .NET CLI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
      
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Restore packages
      working-directory: Collectors
      run: nuget restore AnalyticsCollector.sln
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Build with MSBuild
      working-directory: Collectors/AnalyticsCollector
      run: msbuild  AnalyticsCollector.csproj -p:Configuration=Release
